# Use an official Python runtime as a parent image
FROM tensorflow/tensorflow:2.9.0rc0-jupyter
RUN echo

# User configuration - override with --build-arg
ARG user=myuser
ARG group=mygroup
ARG uid=1000
ARG gid=1000

# Some debs want to interact, even with apt-get install -y, this fixes it
ENV DEBIAN_FRONTEND=noninteractive
ENV HOME=/project

# Install any needed packages from apt
RUN apt-get update && apt-get install -y sudo python3 python3-pip git screen vim
RUN pip install --upgrade pip

# Configure user
RUN groupadd -g $gid $user
RUN useradd -u $uid -g $gid $user
RUN usermod -a -G sudo $user
RUN passwd -d $user

RUN apt-get install -y libsm6 libxrender1 ffmpeg libsm6 libxext6
RUN pip3 install --trusted-host pypi.python.org numpy scipy Pillow cython matplotlib scikit-image keras==2.4.0 opencv-python h5py imgaug IPython progressbar2 pandas sklearn lxml

COPY /snapshots/resnet50_csv_inference_10.h5 /snapshots/resnet50_csv_inference_10.h5

# Need to do both installs to make it work
ADD https://api.github.com/repos/vaneeda/deepvision-retinanet/git/refs/heads/memory_optimization version.json
RUN git clone -b memory_optimization https://github.com/vaneeda/deepvision-retinanet.git

# RUN git clone https://github.com/vaneeda/deepvision-retinanet.git
RUN cd deepvision-retinanet && python setup.py build_ext --inplace
RUN cd deepvision-retinanet && pip3 install . 

# Run when the container launches
CMD ["/bin/bash", "-c", "cd /deepvision-retinanet && python3 keras_retinanet/bin/predict_DV.py"]