# Config file

path_to_data: '/data/'
min_img_size: 1027
score_threshold: 0.05
opt_thresholds: {"maurolicus": 0.200, "periphylla": 0.970, "krill": 0.300, "benthosema": 0.770, "sergestes": 0.470, "gonatus": 0.700}
orientation: ['Left','Right']
xml_file: '/temp/deepvision.xml'
snapshot_path: '/snapshots/resnet50_csv_inference_03.h5'
classes: {0: 'maurolicus', 1: 'periphylla', 2: 'krill', 3: 'benthosema', 4: 'sergestes', 5: 'gonatus'}




