# Config file

path_to_data: '/data/20191205T0014Z/'
path_to_xml: '/temp/20191205T0014Z_temporal_folder_2/'
snapshot_path: '/model/snapshots/resnet50_csv_inference_10.h5'
classes: '/model/fish_4_classes.csv'




